{
 "title": "NestJS Observability",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "staging : staging_ , production : production_"
   },
   { "name": "TimeAgregation", "label": "Time Agregation", "query": "1m, 5m, 20m, 1h" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(${environment}nodejs_version_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Process Restart Times in Time Range",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(${environment}process_start_time_seconds{instance=~\"$instance\"}[$__range]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node.js Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(${environment}nodejs_version_info) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Active Instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(${environment}nodejs_version_info) by (instace)"
    }
   ]
  },
  { "title": "Process Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Process CPU Usage Total",
   "type": "timeseries",
   "description": "This represents the percentage of CPU usage  ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(${environment}process_cpu_seconds_total{instance=~\"$instance\"}[2m]) * 100",
     "legendFormat": "Total CPU - {{instance}}"
    }
   ]
  },
  {
   "title": "Process Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "${environment}process_resident_memory_bytes ",
     "legendFormat": "Process Memory - {{instance}}"
    }
   ]
  },
  {
   "title": "Process CPU Usage Detail",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(${environment}process_cpu_user_seconds_total{instance=~\"$instance\"}[2m]) * 100",
     "legendFormat": "User CPU - {{instance}}"
    },
    {
     "expr": "irate(${environment}process_cpu_system_seconds_total{instance=~\"$instance\"}[2m]) * 100",
     "legendFormat": "Sys CPU - {{instance}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage Detail",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "${environment}process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "Process Memory - {{instance}}"
    },
    {
     "expr": "${environment}nodejs_heap_size_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Total - {{instance}}"
    },
    {
     "expr": "${environment}nodejs_heap_size_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}}"
    },
    {
     "expr": "${environment}nodejs_external_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "External Memory - {{instance}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "${environment}nodejs_eventloop_lag_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "${environment}nodejs_active_handles_total{instance=~\"$instance\"}",
     "legendFormat": "Active Handler - {{instance}}"
    },
    {
     "expr": "${environment}nodejs_active_requests_total{instance=~\"$instance\"}",
     "legendFormat": "Active Request - {{instance}}"
    }
   ]
  },
  {
   "title": "Heap Total Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "${environment}nodejs_heap_space_size_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Total - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "${environment}nodejs_heap_space_size_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Available Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "${environment}nodejs_heap_space_size_available_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}} - {{space}}"
    }
   ]
  },
  { "title": "Requests Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Request Latency (AVG) ${TimeAgregation}",
   "type": "timeseries",
   "description": "Latency average for each endpoint",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(increase(${environment}_http_request_duration_seconds_sum{path!=\"/favicon.ico\"}[${TimeAgregation}])) by (method, path) / sum(increase(${environment}_http_request_duration_seconds_count{path!=\"/favicon.ico\"}[${TimeAgregation}])) by (method, path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Status Code Rate",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(${environment}_http_request_duration_seconds_count{path!~\"/favicon.ico\"}[$__range])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Throughput by status code in ${TimeAgregation}",
   "type": "timeseries",
   "description": "Quantity of requests by status code",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "floor(sum(increase(${environment}_http_request_duration_seconds_count{status_code=~\"2..\"}[${TimeAgregation}])))",
     "legendFormat": "2xx"
    },
    {
     "expr": "floor(sum(increase(${environment}_http_request_duration_seconds_count{status_code=~\"3..\"}[${TimeAgregation}])))",
     "legendFormat": "3xx"
    },
    {
     "expr": "floor(sum(increase(${environment}_http_request_duration_seconds_count{status_code=~\"4..\"}[${TimeAgregation}])))",
     "legendFormat": "4xx"
    },
    {
     "expr": "floor(sum(increase(${environment}_http_request_duration_seconds_count{status_code=~\"5..\"}[${TimeAgregation}])))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Throughput by endpoint in ${TimeAgregation}",
   "type": "timeseries",
   "description": "Quantity of requests by endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "floor(sum(increase(${environment}_http_request_duration_seconds_count{path!~\"/favicon.ico\"}[${TimeAgregation}])) by (method, path))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Http Error in ${TimeAgregation}",
   "type": "timeseries",
   "description": "Error for status code 4xx or 5xx",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "floor(sum(increase(${environment}_http_request_duration_seconds_count{status_code=~\"[4-5]..\"}[${TimeAgregation}])) by (path, status_code))",
     "legendFormat": "{{path}} - {{status_code}}"
    }
   ]
  },
  {
   "title": "Request more than 2s in ${TimeAgregation}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "floor(sum(increase(${environment}_http_request_duration_seconds_bucket{le=\"+Inf\", path!~\"/favicon.ico\"}[${TimeAgregation}])) by (path)\n- \nsum(increase(${environment}_http_request_duration_seconds_bucket{le=\"2\", path!~\"/favicon.ico\"}[${TimeAgregation}])) by (path))\n",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request Rate in ${TimeAgregation}",
   "type": "timeseries",
   "description": "Total of requests in 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "floor(sum(increase(${environment}_http_request_duration_seconds_count[${TimeAgregation}])))"
    }
   ]
  },
  {
   "title": "Total of Requests at Selected Range",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(${environment}_http_request_duration_seconds_count[$__range])))"
    }
   ]
  }
 ]
}